[package]
name = "desktop-agent"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.30.0"
egui = "0.30.0"
futures-util = "0.3.31"
once_cell = "1.20.2"
reqwest = "0.12.12"
serde = "1.0.217"
serde_json = "1.0.137"
tokio = "1.43.0"
tokio-tungstenite = "0.26.1"
